name: CI

on:
    push:
        branches-ignore:
            - main
        branches:
            - *
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK11
              uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'

            - name: Compile sources
              run: mvn -B compile

            - name: executes tests
              run: mvn -B verify
